FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

COPY AK8Api/*.csproj ./AK8Api/

RUN dotnet restore ./AK8Api/AK8Api.csproj

COPY AK8Api/. ./AK8Api/

WORKDIR /src/AK8Api

RUN dotnet publish -c Release -o /app

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS runtime
WORKDIR /app

RUN apt-get update && apt-get install -y curl default-mysql-client

COPY --from=build /app .
COPY AK8Api/appsettings.json ./appsettings.json

EXPOSE 8080

ENTRYPOINT ["dotnet", "AK8Api.dll"]